UK_COUNTIES = [
    ('london_essex', 'London / Essex'),
    ('kent_surrey', 'Kent / Surrey'),
    ('sussex_hampshire', 'Sussex / Hampshire'),
    ('berkshire_oxfordshire', 'Berkshire / Oxfordshire'),
    ('buckinghamshire_hertfordshire', 'Buckinghamshire / Hertfordshire'),
    ('cambridgeshire_suffolk', 'Cambridgeshire / Suffolk'),
    ('norfolk_lincolnshire', 'Norfolk / Lincolnshire'),
    ('northamptonshire_leicestershire', 'Northamptonshire / Leicestershire'),
    ('nottinghamshire_derbyshire', 'Nottinghamshire / Derbyshire'),
    ('warwickshire_worcestershire', 'Warwickshire / Worcestershire'),
    ('west_midlands_staffordshire', 'West Midlands / Staffordshire'),
    ('gloucestershire_wiltshire', 'Gloucestershire / Wiltshire'),
    ('somerset_dorset', 'Somerset / Dorset'),
    ('devon_cornwall', 'Devon / Cornwall'),
    ('cheshire_merseyside', 'Cheshire / Merseyside'),
    ('greater_manchester_lancashire', 'Greater Manchester / Lancashire'),
    ('cumbria_northumberland', 'Cumbria / Northumberland'),
    ('tyne_and_wear_durham', 'Tyne and Wear / Durham'),
    ('north_yorkshire_west_yorkshire', 'North Yorkshire / West Yorkshire'),
    ('south_yorkshire_east_riding', 'South Yorkshire / East Riding'),
    ('north_wales', 'North Wales'),
    ('south_wales', 'South Wales'),
    ('mid_wales', 'Mid Wales'),
    ('south_scotland', 'South Scotland'),
    ('west_scotland', 'West Scotland'),
    ('east_scotland', 'East Scotland'),
    ('north_scotland', 'North Scotland'),
    ('northern_ireland', 'Northern Ireland'),
]
