# Generated by Django 4.2.7 on 2026-07-27 18:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("musician", "Musician"),
                            ("caricaturist", "Caricaturist"),
                            ("photographer", "Photographer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("profile_image", models.ImageField(upload_to="vendors/")),
                (
                    "experience_years",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Caricaturist",
            fields=[
                (
                    "vendor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vendors.vendor",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("realistic", "Realistic"),
                            ("cartoon", "Cartoon"),
                            ("abstract", "Abstract"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("medium", models.CharField(max_length=200)),
                ("rush_delivery_available", models.BooleanField(default=False)),
                ("turnaround_days", models.IntegerField(default=7)),
            ],
            options={
                "verbose_name_plural": "Caricaturists",
            },
            bases=("vendors.vendor",),
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "vendor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vendors.vendor",
                    ),
                ),
                ("instruments", models.CharField(max_length=200)),
                ("genres", models.CharField(max_length=200)),
                ("can_provide_sound_system", models.BooleanField(default=False)),
                (
                    "ensemble_size",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Musicians",
            },
            bases=("vendors.vendor",),
        ),
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "vendor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vendors.vendor",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("portrait", "Portrait"),
                            ("wedding", "Wedding"),
                            ("event", "Event"),
                            ("landscape", "Landscape"),
                            ("product", "Product"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_second_shooter", models.BooleanField(default=False)),
                ("drone_available", models.BooleanField(default=False)),
                (
                    "photos_included",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("editing_style", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Photographers",
            },
            bases=("vendors.vendor",),
        ),
        migrations.CreateModel(
            name="VendorPortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="portfolio/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("vendor", "customer")},
            },
        ),
        migrations.CreateModel(
            name="VendorCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("license", "License"),
                            ("insurance", "Insurance"),
                            ("certification", "Certification"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("document", models.FileField(upload_to="certificates/")),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="vendors.musician",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
    ]
