# Generated by Django 4.2.7 on 2026-07-27 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="act_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="vendor",
            name="act_types",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="vendor",
            name="home_country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="home_county",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="number_of_members",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="stage_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="vendor",
            name="start_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
