# Generated by Django 4.2.7 on 2026-07-27 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vendors",
            "0002_vendor_act_name_vendor_act_types_vendor_home_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="can_provide_lighting_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="musician",
            name="lighting_system_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="musician",
            name="sound_system_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="musician",
            name="ensemble_size",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
