# Generated by Django 4.2.7 on 2026-08-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_vendor_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="testimonial_1_event_type",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_1_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_1_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_2_event_type",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_2_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_2_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_3_event_type",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_3_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="testimonial_3_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
