# Generated by Django 4.2.7 on 2026-08-11 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_enquirynotification_notification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendors", "0007_vendor_testimonial_1_event_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vendorreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vendor",
            name="act_name_is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorreview",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorreview",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_review_moderations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendorreview",
            name="customer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="vendorreview",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="vendorreview",
            name="enquiry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_review",
                to="bookings.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="vendorreview",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vendorreview",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
