# Generated by Django 4.2.7 on 2026-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0008_alter_vendorreview_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="county_pricing",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
