# Generated by Django 4.2.7 on 2026-08-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0009_vendor_county_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorUnavailableDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailable_dates",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor unavailable date",
                "verbose_name_plural": "Vendor unavailable dates",
                "ordering": ["date", "id"],
                "unique_together": {("vendor", "date")},
            },
        ),
    ]
