# Generated by Django 4.2.7 on 2026-07-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=20)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("event_type", models.CharField(max_length=200)),
                ("event_location", models.CharField(max_length=300)),
                ("venue_name", models.CharField(blank=True, max_length=200)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "details",
                    models.TextField(
                        help_text="Additional information about the event and requirements"
                    ),
                ),
                ("special_requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Awaiting Vendor Response"),
                            ("viewed", "Viewed by Vendor"),
                            ("available", "Available - Vendor Confirmed"),
                            ("unavailable", "Unavailable - Vendor Declined"),
                            ("booked", "Booked - Contract Signed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vendor_viewed", models.BooleanField(default=False)),
                ("vendor_viewed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor_response",
                    models.TextField(
                        blank=True, help_text="Vendor's response to the enquiry"
                    ),
                ),
                ("vendor_availability_note", models.TextField(blank=True)),
                ("admin_notified", models.BooleanField(default=False)),
                ("admin_notified_date", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Admin notes for follow-up"),
                ),
                ("needs_followup", models.BooleanField(default=True)),
                ("followup_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("awaiting", "Awaiting Confirmation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_message", models.TextField()),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("response_date", models.DateTimeField(auto_now_add=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="bookings.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-response_date"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("vendor_new_enquiry", "New Enquiry for Vendor"),
                            ("admin_new_enquiry", "New Enquiry Alert for Admin"),
                            (
                                "customer_confirmation",
                                "Enquiry Confirmation to Customer",
                            ),
                            ("vendor_accepted", "Vendor Accepted Enquiry"),
                            ("vendor_declined", "Vendor Declined Enquiry"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(max_length=200)),
                ("sent", models.BooleanField(default=False)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="bookings.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_date"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("admin_to_vendor", "Admin Follow-up with Vendor"),
                            ("admin_to_customer", "Admin Follow-up with Customer"),
                            ("vendor_reminder", "Vendor Reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("scheduled_date", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="bookings.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
    ]
