# Generated by Django 4.2.7 on 2026-08-11 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0007_vendor_testimonial_1_event_type_and_more"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirynotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("vendor_new_enquiry", "New Enquiry for Vendor"),
                    ("admin_new_enquiry", "New Enquiry Alert for Admin"),
                    ("customer_confirmation", "Enquiry Confirmation to Customer"),
                    ("vendor_accepted", "Vendor Accepted Enquiry"),
                    ("vendor_declined", "Vendor Declined Enquiry"),
                    (
                        "customer_review_request",
                        "Post-Event Review Request to Customer",
                    ),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("scheduled_send_at", models.DateTimeField()),
                ("email_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("review_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_request",
                        to="bookings.enquiry",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
