# Generated by Django 4.2.7 on 2026-08-11 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0002_alter_enquirynotification_notification_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunnelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=80)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("context", models.CharField(blank=True, max_length=120)),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("vendor_type", models.CharField(blank=True, max_length=50)),
                ("href", models.CharField(blank=True, max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funnel_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
